# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
